# Generated by Django 5.2.10 on 2026-02-02 04:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(help_text='Nombre del icono (FontAwesome/Lucide)', max_length=50)),
                ('color_hex', models.CharField(default='#3b82f6', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('puntos_explorador', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('descripcion', models.TextField()),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('rango_precios', models.IntegerField(help_text='Escala del 1 al 4', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('contacto', models.JSONField(default=dict, help_text="Estructura: {'ig': '@...', 'wsp': '...'}")),
                ('horarios', models.JSONField(default=dict, help_text="Estructura: {'lunes': '09:00-18:00'}")),
                ('verificado', models.BooleanField(default=False)),
                ('url_imagen', models.URLField(blank=True, max_length=500, null=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to='api.categoria')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas_sugeridas', to='api.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.perfil')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.tienda')),
            ],
            options={
                'verbose_name': 'Reseña',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segmento_calle', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='api.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='api.perfil')),
            ],
            options={
                'unique_together': {('usuario', 'tienda')},
            },
        ),
    ]
