# Generated by Django 5.2.10 on 2026-02-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='latitud',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='longitud',
            field=models.DecimalField(decimal_places=16, max_digits=21),
        ),
    ]
