# Generated by Django 5.2.10 on 2026-02-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='categoria',
        ),
        migrations.AddField(
            model_name='tienda',
            name='categorias',
            field=models.ManyToManyField(related_name='tiendas', to='api.categoria'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección / Pasaje'),
        ),
    ]
