# Generated by Django 5.2.10 on 2026-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_tienda_categoria_tienda_categorias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='contacto',
            field=models.JSONField(blank=True, default=dict, help_text="Estructura: {'ig': '@...', 'wsp': '...'}", null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='horarios',
            field=models.JSONField(blank=True, default=dict, help_text="Estructura: {'lunes': '09:00-18:00'}", null=True),
        ),
    ]
