# Generated by Django 5.2.10 on 2026-02-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tienda_contacto_alter_tienda_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
