# Generated by Django 5.2.10 on 2026-02-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tienda_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tiendas/fotos/'),
        ),
    ]
