# Generated by Django 5.2.10 on 2026-02-25 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tienda_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaExploracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Avenida del Mar - Tramo 1', max_length=150)),
                ('coordenadas', models.JSONField(default=list)),
                ('estado', models.CharField(choices=[('verde', 'Completado (Todas las tiendas anotadas)'), ('amarillo', 'Incompleto (Faltan tiendas por anotar)')], default='verde', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.perfil')),
            ],
        ),
    ]
